# Generated by Django 6.0.7 on 2026-07-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0002_alter_hero_options_alter_innerhero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name=' منتشر شده'),
        ),
    ]
