# Generated by Django 6.0.7 on 2026-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0003_blog_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='card_type',
            field=models.CharField(choices=[('normal', 'نرمال'), ('small', 'کوچک'), ('tall', 'بلند'), ('wide', 'عریض')], default='normal', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='امتیاز'),
        ),
    ]
