# Generated by Django 6.0.7 on 2026-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='working_hours',
            field=models.TextField(verbose_name='ساعات کاری'),
        ),
    ]
