# Generated by Django 6.0.7 on 2026-09-17 15:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0006_alter_sitesetting_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='button_text',
        ),
        migrations.AddField(
            model_name='hero',
            name='primary_button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='hero',
            name='primary_button_text',
            field=models.CharField(default='رزرو نوبت', max_length=50, verbose_name='متن دکمه اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه دوم'),
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_button_text',
            field=models.CharField(default='مشاهده نمونه کارها', max_length=50, verbose_name='متن دکمه دوم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن مقاله'),
        ),
    ]
