# Generated by Django 6.0.7 on 2026-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0007_remove_hero_button_link_remove_hero_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.PositiveIntegerField(default=250000, verbose_name='قیمت پایه'),
            preserve_default=False,
        ),
    ]
