# Generated by Django 6.0.7 on 2026-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0008_service_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_on_pricing',
            field=models.BooleanField(default=False, verbose_name='نمایش در تعرفه\u200cها'),
        ),
    ]
