# Generated by Django 6.0.7 on 2026-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nailApp', '0009_service_show_on_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='پرطرفدار'),
        ),
    ]
